### ISSUE TITLE
[e10s] Links loaded from private about:newtab page becomes non-private in Firefox 45+

### ISSUE THREAD

**Issue by ptcong** [Infocatcher/Private_Tab#202]
I really like this add-on but it seems does not work on Firefox developer edition.

Cookies from normal tab still exists when i open a private tab.

**Comment by Infocatcher** [comment]
Most likely this is due to enabled multi-process mode (Options – General – Enable multi-process …).
Looks like something is broken now and "private" flag will be removed from pages like about:newtab.
So, it's still possible to open about:newtab in private tab, but something went wrong, if you try to load some http… page in that tab.

**Comment by ptcong** [comment]
Thanks for your fixes @Infocatcher
