### ISSUE TITLE
Protocol private:

### ISSUE THREAD

**Issue by niceboy76** [Infocatcher/Private_Tab#247]
With Palemoon 26.5, the protocol private: was ok. Now I have updated to 27.1 and this protocol isn't recognized.

Error description in page : 

Malformed URI: https://addons.mozilla.org/
Usage example: private:https://addons.mozilla.org/ 

Thanks in advance for your answer.

Best Regards.

Nice B

**Comment by JustOff** [comment]
This is likely because newChannelFromURIWithLoadInfo which is already exists in FF37+ [throws an error](https://github.com/Infocatcher/Private_Tab/blob/master/protocolRedirect.html#L31) if second argument (aLoadInfo) is null and [FF<44](https://bugzilla.mozilla.org/show_bug.cgi?id=1182571).

**Comment by Infocatcher** [comment]
That is, this was caused by fix for `nsIIOService.newChannelFromURI()` deprecation: #215.
Now should be fixed: 5df97c5063d758d1c817fab11ed87d1399281859

Test version: <a href="http://infocatcher.ucoz.net/temp/pt/private_tab-0.2.1.3pre-fx-sm.xpi">private_tab-0.2.1.3pre-fx-sm.xpi</a> (<a href="https://github.com/Infocatcher/Private_Tab/tree/c4dccba7dcf256e0ca31be8c59997c6878e66956">source code</a>)
