### ISSUE TITLE
Not working with Firefox Quantum (official release 57)

### ISSUE THREAD

**Issue by toddZilla0130** [Infocatcher/Private_Tab#284]
Relegated to "legacy" status. Hope this comes back quickly - I rely heavily on this extension.

Thanks!

**Comment by inoyakaigor** [comment]
@toddZilla0130 you can follow the migration process in this ticket #254

**Comment by Infocatcher** [comment]
Sorry, not possible to do anything without changes from Firefox side. :(

**Comment by Tallefer** [comment]
@Infocatcher are you planning to work more on any of your addons for the pre-57 Firefox users?

**Comment by Infocatcher** [comment]
> are you planning to work more on any of your addons for the pre-57 Firefox users?

I'm not really sure about future of pre-57 and forks, but I prefer full-featured extensions and still not use Firefox 57 myself. So, yes. Because it's very sad to drop some years of work.
At least until landing of some better WebExtensions API (for now even not fully implemented Chrome API and <a href="https://github.com/mdn/webextensions-examples/blob/master/context-menu-copy-link-with-types/background.js#L14">some trivial things is a mess</a>).

By the way, it's possible (with some hacks) to use old style extensions in Firefox 57, but XPCOM APIs becomes very unstable.

**Comment by Tallefer** [comment]
> I'm not really sure about future of pre-57 and forks, but I prefer full-featured extensions and still not use Firefox 57 myself. So, yes. Because it's very sad to drop some years of work.
Thank you, and I am totally with you on this, dropping so much man-hours seems just crazy. 
Let's just hope there will be a much better API available by the time of next major ESR release.
Also, in the meantime, Palemoon/Waterfox devs are trying to help authors to port addons to their browsers. So, at least some (more or less) active "old" addons won't be lost when Mozilla pulls the plug.
